import { copyFileSync, writeFileSync } from 'node:fs';
import { siteHeader } from './navigation.mjs';

const image = (src, alt, className = '') => `<img class="${className}" src="./assets/${src}" alt="${alt}" loading="lazy">`;
const card = (title, copy) => `<article class="detail-card"><h3>${title}</h3><p>${copy}</p></article>`;
function page(file, title, description, content) {
  return `<!doctype html><html lang="en-US"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#0a0a0c"><meta name="description" content="${description}"><title>${title} | Splatico</title><link rel="icon" href="./assets/favicon.png"><link rel="stylesheet" href="./styles.css"><script src="./main.js" defer></script></head><body><a class="skip-link" href="#main">Skip to content</a>${siteHeader(file)}<main id="main" class="feature-page">${content}</main><footer class="shell site-footer flex flex-wrap items-center justify-between gap-5"><a href="./index.html">SPLATICO</a><div class="flex flex-wrap gap-6"><a href="./index.html#press">PRESS & CREATORS</a><a href="https://splatico.fandom.com/wiki/Splatico_Wiki" target="_blank" rel="noopener noreferrer">WIKI</a><a href="mailto:press@splaticogame.com">CONTACT</a></div></footer></body></html>`;
}
const pages = {
  'map-editor.html': ['Map Editor', 'Build voxel maps, import custom blocks, props, assets, and decals, create models with the Splatico Blockbench plugin, and share on Steam Workshop.', `
    <section class="shell feature-hero grid items-center gap-10 lg:grid-cols-2"><div><p class="eyebrow">MAP EDITOR / STEAM WORKSHOP</p><h1>BUILD YOUR<br><span class="purple-text">NEXT HUNT.</span></h1><p>Build a voxel world. Import your own creations.<br>Make new hiding spots for your friends.</p><div class="editor-hero-actions flex flex-wrap gap-4"><a class="pixel-button button-purple" href="#custom-content">CUSTOM IMPORTS</a><a class="pixel-button button-dark" href="#blockbench">BLOCKBENCH PLUGIN</a></div></div><div class="feature-image">${image('map-editor.png', 'Splatico map editor with its asset browser open')}</div></section>
    <section class="shell section-space"><div class="section-heading"><h2>FROM BLOCKS TO A BATTLEGROUND.</h2></div><div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">${card('BUILD WITH BLOCKS', 'Shape rooms, floors, pools, and entire worlds.')}${card('FILL IT WITH PROPS', 'Place furniture, decorations, and plenty of distractions.')}${card('SET THE SCENE', 'Change the sky, lighting, fog, and weather.')}${card('MAKE IT PLAYABLE', 'Place spawns and test your hiding spots in the game.')}</div></section>
    <section id="custom-content" class="shell section-space editor-imports"><div class="section-heading flex flex-wrap items-end justify-between gap-5"><div><p class="eyebrow">CUSTOM IMPORTS</p><h2>YOUR IDEAS.<br><span class="purple-text">IN THE GAME.</span></h2></div><p class="section-intro">New textures. New props. Your own scenery.<br> Bring it all into the map editor.</p></div><div class="grid gap-6 md:grid-cols-2">${[
      ['blocks-import.png', 'Splatico custom block importer showing a brick texture and five block shapes', 'CUSTOM BLOCKS', 'Import 16×16 textures. Build with cubes, slabs, stairs, ramps, and walls.', 'Separate top, side, and bottom textures.', 'orange'],
      ['props-import.png', 'A custom wooden chair preview in the Splatico prop importer', 'CUSTOM PROPS', 'Make objects players can disguise as. Import your Blockbench creations and hide among them.', 'Optional idle and movement animations.', 'purple'],
      ['assets-import.png', 'A custom table preview in the Splatico asset importer', 'CUSTOM ASSETS', 'Add your own furniture, plants, and scenery. Build out the world around the hunt.', 'Add seats, glowing textures, and collision settings.', 'blue'],
      ['decals-placement.png', 'A rug made from custom decal tiles on a library floor', 'CUSTOM DECALS', 'Import 16×16 images for signs, posters, arrows, and surface details.', 'Place on block faces and rotate to fit.', 'pink']
    ].map(([src, alt, title, copy, note, accent]) => `<article class="detail-card import-card import-${accent}"><div class="import-image">${image(src, alt)}</div><div class="import-copy"><h3>${title}</h3><p>${copy}</p><p class="import-note">${note}</p></div></article>`).join('')}</div></section>
    <section id="blockbench" class="shell section-space compact-top"><div class="detail-banner blockbench-banner"><div><p class="eyebrow">SPLATICO BLOCKBENCH PLUGIN</p><h2>MAKE IT.<br><span class="purple-text">IMPORT IT. PLAY IT.</span></h2><p>Model and texture your own props and scenery in Blockbench. Export straight to a Splatico package, then import it into your map.</p><a class="pixel-button button-purple" href="https://github.com/splatico/Splatico-Blockbench-Plugin" target="_blank" rel="noopener noreferrer">DOWNLOAD THE PLUGIN</a><p class="plugin-compatibility">Works in desktop and web Blockbench.</p></div></div></section>
    <section class="shell feature-two-images grid gap-6 md:grid-cols-2"><figure class="feature-image">${image('library.png', 'A Splatico library map')}<figcaption>THE LIBRARY</figcaption></figure><figure class="feature-image">${image('pool.png', 'A Splatico swimming pool map')}<figcaption>SWIMMING POOL</figcaption></figure></section>
    <section id="workshop" class="shell section-space"><div class="detail-banner grid items-center gap-8 md:grid-cols-2"><div><p class="eyebrow">STEAM WORKSHOP SUPPORT</p><h2>BUILD IT.<br>SHARE IT. PLAY IT.</h2><p>Publish your maps to Steam Workshop. Your custom blocks, props, assets, and decals are included with the map.</p></div><div><h3>MORE MAPS. MORE HIDING SPOTS.</h3><p>Subscribe to community maps and bring them into your next game. Your friends get the same map and custom content.</p><a class="pixel-button button-orange" href="./index.html#community">JOIN THE COMMUNITY</a></div></div></section>`],
  'customization.html': ['Character Customization', 'Make your Splatico character yours with hats, faces, face colors, and emotes.', `
    <section class="shell feature-hero grid items-center gap-10 lg:grid-cols-2"><div><p class="eyebrow">CHARACTER CUSTOMIZATION</p><h1>LOOK GOOD.<br><span class="orange-text">GET SPLATTED.</span></h1><p>Hats, faces, colors, and emotes.<br>Pick a look before you join the hunt.</p><a class="pixel-button button-orange" href="#hats">CHECK THE HATS</a></div><div class="feature-character-stage">${image('hat-crown.png', 'Splatico character wearing a crown')}<span aria-hidden="true">YOUR LOOK</span></div></section>
    <section id="hats" class="shell section-space"><div class="section-heading"><p class="eyebrow">HATS</p><h2>TOP IT OFF.</h2></div><div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-4 character-grid">${[['hat-paint.png','PAINT BUCKET'],['hat-crown.png','CROWN'],['hat-mushroom.png','MUSHROOM'],['hat-cat.png','CAT EARS']].map(([src,name]) => `<figure class="character-tile">${image(src, 'Character wearing '+name.toLowerCase())}<figcaption>${name}</figcaption></figure>`).join('')}</div><p class="feature-note">Choose from your available hats. Earn more by playing.</p></section>
    <section id="faces" class="shell section-space compact-top"><div class="section-heading"><p class="eyebrow">FACES</p><h2>WEAR YOUR MOOD.</h2></div><div class="grid gap-5 sm:grid-cols-3 character-grid">${[['face-happy.png','HAPPY'],['face-angry.png','ANGRY'],['face-wink.png','WINK']].map(([src,name]) => `<figure class="character-tile face-tile">${image(src, 'Character with a '+name.toLowerCase()+' expression')}<figcaption>${name}</figcaption></figure>`).join('')}</div></section>
    <section class="shell section-space compact-top"><div class="detail-banner grid items-center gap-8 md:grid-cols-2"><div><p class="eyebrow">COLORS & EMOTES</p><h2>ADD SOME PERSONALITY.</h2><p>Change your face color.<br>Wave, dance, flex, or pull off a backflip.</p><div class="color-swatches" aria-label="Example character colors"><span style="background:#f45100" aria-label="Orange"></span><span style="background:#0055f4" aria-label="Blue"></span><span style="background:#6ee31c" aria-label="Green"></span><span style="background:#7a3cc4" aria-label="Purple"></span></div></div><div class="emote-image">${image('point.png','Splatico character pointing with a wink')}</div></div></section>`],
  'game-modes.html': ['Game Modes', 'Play Infection, Last Stand, Rush, and VIP in Splatico multiplayer voxel prop hunt.', `
    <section class="shell feature-hero grid items-center gap-10 lg:grid-cols-2"><div><p class="eyebrow">MULTIPLAYER VOXEL PROP HUNT</p><h1>FOUR MODES.<br><span class="orange-text">ONE MESSY HUNT.</span></h1><p>Hide as a prop or hunt with paint.<br>Pick the rules that suit your group.</p><a class="pixel-button button-orange" href="#infection">EXPLORE THE MODES</a></div><div class="feature-image">${image('pool.png', 'Swimming pool map with scattered props')}</div></section>
    <section class="shell section-space"><div class="grid gap-6 md:grid-cols-2 mode-details">
      <article id="infection" class="detail-card mode-detail infection"><p class="eyebrow">INFECTION</p><h2>THE HUNT GROWS.</h2><p>Every caught prop becomes a hunter. Props survive until time runs out. Hunters win by finding them all.</p><div class="rule-tag">CAUGHT? SWITCH TEAMS.</div></article>
      <article id="last-stand" class="detail-card mode-detail last-stand"><p class="eyebrow">LAST STAND</p><h2>ONE LIFE PER ROUND.</h2><p>Get caught and you're out until the next round. Win more rounds than the other team in a best-of series.</p><div class="rule-tag">NO RESPAWNS.</div></article>
      <article id="rush" class="detail-card mode-detail rush"><p class="eyebrow">RUSH</p><h2>KEEP THE TICKETS.</h2><p>Props respawn, but each catch costs the team a ticket. Hunters empty the ticket pool. Props hold on until time runs out.</p><div class="rule-tag">RESPAWN. HIDE AGAIN.</div></article>
      <article id="vip" class="detail-card mode-detail vip"><p class="eyebrow">VIP</p><h2>PROTECT THE SECRET VIP.</h2><p>One prop is the VIP. Hunters try to catch them. Props keep them hidden to win the interval. Caught props respawn.</p><div class="rule-tag">ONE PROP MATTERS MOST.</div></article>
    </div></section><section class="shell section-space compact-top"><div class="detail-banner"><p class="eyebrow">YOUR LOBBY. YOUR RULES.</p><h2>ADD A LITTLE CHAOS.</h2><p>Adjust the mode rules, or throw events into the round.</p><a class="pixel-button button-pink" href="./chaos.html">EXPLORE CHAOS MODIFIERS</a></div></section>`],
  'chaos.html': ['Chaos Modifiers', 'Change the conditions mid-round with low gravity, prop rain, lights out, and more Splatico chaos events.', `
    <section class="shell feature-hero grid items-center gap-10 lg:grid-cols-2"><div><p class="eyebrow">CHAOS MODIFIERS</p><h1>EXPECT<br><span class="pink-text">THE UNEXPECTED.</span></h1><p>The hunt is on. Then the rules change.<br>Pick your events and turn up the frequency.</p><a class="pixel-button button-pink" href="#events">SEE THE EVENTS</a></div><div class="chaos-art"><img class="chaos-backdrop" src="./assets/pool.png" alt=""><img class="chaos-character" data-parallax="18" src="./assets/jump.png" alt="A Splatico character jumping"><span class="chaos-chip chip-gravity">LOW GRAVITY</span><span class="chaos-chip chip-rain">PROP RAIN</span></div></section>
    <section id="events" class="shell section-space"><div class="section-heading"><h2>SWITCH UP THE HUNT.</h2></div><div class="grid gap-5 sm:grid-cols-2 lg:grid-cols-3 chaos-details">${[
      ['LOW GRAVITY','Jump higher. Fall slower.'],['SLIPPERY FLOOR','The floor turns to ice. Try to stay in control.'],['SPEED CHAOS','Everyone speeds up or slows down.'],['PROP SHUFFLE','Hidden props spin to face a new direction.'],['EXTRA DECOYS','Every prop gets an extra decoy.'],['TANK REFILLER','Hunters get their paint tank and blast refilled.'],['HUNTER BLASTER','Air blasts reach further and hit harder.'],['GOO DAMAGE','Goo eats props twice as fast.'],['PROP RAIN','Extra props fall from above.'],['PROP SWAP','Some map props turn into different props.'],['LIGHTS OUT','The map goes dark.'],['FOG','Thick fog cuts down visibility.'],['SKY SWAP','A new sky for the rest of the round.']
    ].map(([title,copy]) => card(title,copy)).join('')}</div></section><section class="shell section-space compact-top"><div class="detail-banner"><p class="eyebrow">HOST SETTINGS</p><h2>A LITTLE CHAOS. OR A LOT.</h2><p>Keep it disabled, use normal events, or choose a custom set.<br>Set the frequency to Rare, Frequent, or Insane.</p><a class="pixel-button button-orange" href="./game-modes.html">CHOOSE YOUR GAME MODE</a></div></section>`],
};
export function buildFeaturePages() {
  for (const [file, [title, description, content]] of Object.entries(pages)) writeFileSync(`dist/${file}`, page(file, title, description, content));
  // Preserve existing links while all content and navigation use American English.
  copyFileSync('dist/customization.html', 'dist/customisation.html');
}
